import os
import json
import requests
import config
from core.hud_server import HUDServer, TELEMETRY_LOGS

class PromptOptimizer:
    TEMPLATE_PATH = "D:/Visual Studio/Cipher-AI/core/prompt_templates.json"

    @classmethod
    def optimize_system_prompts(cls) -> bool:
        """
        Analyzes recent telemetry logs for crash patterns or excessive retry loops,
        and leverages a local critic model to refine baseline system prompt phrasings.
        """
        print("🧠 [METACOGNITION]: Initializing automated self-optimization pass...")
        
        # Count failures or retries from the active active log cache
        log_snapshot = list(TELEMETRY_LOGS)
        crash_count = sum(1 for log in log_snapshot if "CRASH CAUGHT" in log or "failed execution" in log)
        
        if crash_count == 0:
            print("✅ [METACOGNITION]: System metrics show optimal stability. Prompt adjustments bypassed.")
            HUDServer.push_log("🧠 METACONGITION: Prompt optimization check passed at 100% efficiency.")
            return True

        print(f"🔍 [METACOGNITION]: Detected {crash_count} optimization triggers. Adjusting system prompt models...")
        HUDServer.push_log("🧠 METACONGITION: Architectural adjustments triggered by telemetry anomalies.")

        if not os.path.exists(cls.TEMPLATE_PATH):
            return False

        try:
            with open(cls.TEMPLATE_PATH, "r", encoding="utf-8") as f:
                templates = json.load(f)

            current_prompt = templates.get("coding_skill_base", "")
            model = getattr(config, "LLM_MODEL", "qwen2.5-coder:1.5b")
            url = f"{getattr(config, 'OLLAMA_URL', 'http://localhost:11434')}/api/generate"

            # Formulate meta-prompting directive instructing the local model to optimize its own rules
            critic_prompt = f"""You are Cipher's internal Metacognitive Prompt Engineer. The current system prompt for your CodeAnalyst agent has resulted in runtime compile failures. 

Current System Prompt:
"{current_prompt}"

Telemetry logs caught multiple errors during active file evaluation sweeps. Rewrite this system prompt to be more direct, adding explicit structural strictness regarding syntax corrections, delimiter precision, or variable validation rules.

Output ONLY the raw text of the newly optimized system prompt. Do not wrap it in quotes, markdown code blocks, or conversational commentary."""

            response = requests.post(
                url,
                json={"model": model, "prompt": critic_prompt, "stream": False},
                timeout=120
            )

            if response.status_code == 200:
                optimized_prompt = response.json().get("response", "").strip()
                # Clean loose formatting markers sometimes generated by small models
                optimized_prompt = optimized_prompt.replace('"', '').replace('```', '')

                if optimized_prompt and len(optimized_prompt) > 20:
                    templates["coding_skill_base"] = optimized_prompt
                    
                    # Persist the newly evolved genetic memory back to disk
                    with open(cls.TEMPLATE_PATH, "w", encoding="utf-8") as w_f:
                        json.dump(templates, w_f, indent=2)
                        
                    print("✨ [METACOGNITION COMPLETED]: System template prompts evolved and re-indexed to disk.")
                    HUDServer.push_log("✨ METACOGNITION SUCCESS: Optimized CodeAnalyst system prompt configuration.")
                    return True

        except Exception as e:
            print(f"❌ [METACOGNITION CRASH]: Self-optimization pipeline failed: {str(e)}")
            
        return False
