"""
Cipher Skill — PPTX Forge
Organ: The Presenter
Voice-driven PowerPoint presentation generator.
Uses python-pptx — fully offline, zero API keys, zero cloud.
16GB RAM build: no restrictions on slide count or content depth.
"""

import os
import re
from datetime import datetime


OUTPUT_DIR = "generated_code"  # Reuse Cipher's existing output directory
DEFAULT_SLIDE_COUNT = 6


class PptxForgeSkill:
    def __init__(self):
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        print(">> PPTX Forge: ONLINE")

    def execute(self, command: str) -> str | None:
        cmd = command.lower().strip()

        triggers = [
            "create presentation",
            "make presentation",
            "generate presentation",
            "create slides",
            "make slides",
            "generate slides",
            "create pptx",
            "make pptx",
            "build presentation",
            "presentation about",
            "slides about",
        ]

        matched = next((t for t in triggers if t in cmd), None)
        if not matched:
            return None

        # Extract topic — everything after the trigger phrase
        topic = command
        for t in triggers:
            topic = re.sub(re.escape(t), "", topic, flags=re.IGNORECASE).strip()

        # Clean leftover filler words
        topic = re.sub(r'^(about|on|for|the|a|an)\s+', '', topic, flags=re.IGNORECASE).strip()

        if not topic:
            return "What topic should I build a presentation about?"

        return self._generate_presentation(topic)

    def _generate_presentation(self, topic: str) -> str:
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt, Emu
            from pptx.dml.color import RGBColor
            from pptx.enum.text import PP_ALIGN
        except ImportError:
            return "python-pptx not installed. Run: pip install python-pptx"

        try:
            # Generate slide content using TurboBrain
            slides_data = self._generate_content(topic)

            prs = Presentation()
            prs.slide_width = Inches(13.33)
            prs.slide_height = Inches(7.5)

            # Color palette — dark professional theme
            COLOR_BG_DARK     = RGBColor(0x0D, 0x0D, 0x1A)   # Near-black navy
            COLOR_BG_SLIDE    = RGBColor(0x12, 0x12, 0x2B)   # Dark blue-black
            COLOR_ACCENT      = RGBColor(0x00, 0xD4, 0xFF)   # Cyan accent
            COLOR_ACCENT2     = RGBColor(0x7B, 0x2F, 0xFF)   # Purple accent
            COLOR_WHITE       = RGBColor(0xFF, 0xFF, 0xFF)
            COLOR_SUBTEXT     = RGBColor(0xAA, 0xAA, 0xCC)

            blank_layout = prs.slide_layouts[6]  # Completely blank

            # ── TITLE SLIDE ──────────────────────────────────────────────
            slide = prs.slides.add_slide(blank_layout)
            self._fill_background(slide, COLOR_BG_DARK)

            # Accent bar left edge
            self._add_rect(slide, 0, 0, Inches(0.15), Inches(7.5), COLOR_ACCENT)
            # Accent bar bottom
            self._add_rect(slide, 0, Inches(6.8), Inches(13.33), Inches(0.08), COLOR_ACCENT2)

            # Title text
            title_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.2), Inches(12), Inches(1.8))
            tf = title_box.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.alignment = PP_ALIGN.LEFT
            run = p.add_run()
            run.text = slides_data["title"]
            run.font.size = Pt(44)
            run.font.bold = True
            run.font.color.rgb = COLOR_WHITE

            # Subtitle
            sub_box = slide.shapes.add_textbox(Inches(0.5), Inches(4.1), Inches(10), Inches(0.8))
            tf2 = sub_box.text_frame
            p2 = tf2.paragraphs[0]
            run2 = p2.add_run()
            run2.text = slides_data.get("subtitle", f"Generated by Cipher AI")
            run2.font.size = Pt(18)
            run2.font.color.rgb = COLOR_ACCENT

            # Date stamp
            date_box = slide.shapes.add_textbox(Inches(0.5), Inches(6.5), Inches(6), Inches(0.4))
            tf3 = date_box.text_frame
            p3 = tf3.paragraphs[0]
            run3 = p3.add_run()
            run3.text = datetime.now().strftime("%B %Y")
            run3.font.size = Pt(11)
            run3.font.color.rgb = COLOR_SUBTEXT

            # ── CONTENT SLIDES ────────────────────────────────────────────
            for i, slide_data in enumerate(slides_data["slides"]):
                slide = prs.slides.add_slide(blank_layout)
                self._fill_background(slide, COLOR_BG_SLIDE)

                # Top accent bar
                self._add_rect(slide, 0, 0, Inches(13.33), Inches(0.08), COLOR_ACCENT)
                # Slide number pill bottom right
                num_box = slide.shapes.add_textbox(Inches(12.2), Inches(7.0), Inches(0.9), Inches(0.35))
                tf_n = num_box.text_frame
                p_n = tf_n.paragraphs[0]
                p_n.alignment = PP_ALIGN.CENTER
                r_n = p_n.add_run()
                r_n.text = f"{i + 1}"
                r_n.font.size = Pt(10)
                r_n.font.color.rgb = COLOR_SUBTEXT

                # Slide heading
                head_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.25), Inches(12), Inches(0.9))
                tf_h = head_box.text_frame
                p_h = tf_h.paragraphs[0]
                p_h.alignment = PP_ALIGN.LEFT
                r_h = p_h.add_run()
                r_h.text = slide_data["heading"]
                r_h.font.size = Pt(28)
                r_h.font.bold = True
                r_h.font.color.rgb = COLOR_ACCENT

                # Divider line under heading
                self._add_rect(slide, Inches(0.5), Inches(1.2), Inches(12.3), Inches(0.025), COLOR_ACCENT2)

                # Bullet points
                bullets = slide_data.get("bullets", [])
                y_start = Inches(1.4)
                bullet_height = Inches(0.72)

                for j, bullet in enumerate(bullets[:7]):  # Max 7 bullets per slide
                    bullet_box = slide.shapes.add_textbox(
                        Inches(0.65),
                        y_start + (j * bullet_height),
                        Inches(12.0),
                        bullet_height
                    )
                    tf_b = bullet_box.text_frame
                    tf_b.word_wrap = True
                    p_b = tf_b.paragraphs[0]
                    p_b.alignment = PP_ALIGN.LEFT

                    # Bullet marker in accent color
                    r_dot = p_b.add_run()
                    r_dot.text = "▸  "
                    r_dot.font.size = Pt(13)
                    r_dot.font.color.rgb = COLOR_ACCENT

                    # Bullet text
                    r_bt = p_b.add_run()
                    r_bt.text = bullet
                    r_bt.font.size = Pt(15)
                    r_bt.font.color.rgb = COLOR_WHITE

            # ── CLOSING SLIDE ─────────────────────────────────────────────
            slide = prs.slides.add_slide(blank_layout)
            self._fill_background(slide, COLOR_BG_DARK)
            self._add_rect(slide, 0, 0, Inches(0.15), Inches(7.5), COLOR_ACCENT2)
            self._add_rect(slide, 0, Inches(6.8), Inches(13.33), Inches(0.08), COLOR_ACCENT)

            close_box = slide.shapes.add_textbox(Inches(1.0), Inches(2.8), Inches(11), Inches(1.5))
            tf_c = close_box.text_frame
            p_c = tf_c.paragraphs[0]
            p_c.alignment = PP_ALIGN.CENTER
            r_c = p_c.add_run()
            r_c.text = slides_data.get("closing", "Thank You")
            r_c.font.size = Pt(40)
            r_c.font.bold = True
            r_c.font.color.rgb = COLOR_WHITE

            sig_box = slide.shapes.add_textbox(Inches(1.0), Inches(4.5), Inches(11), Inches(0.5))
            tf_s = sig_box.text_frame
            p_s = tf_s.paragraphs[0]
            p_s.alignment = PP_ALIGN.CENTER
            r_s = p_s.add_run()
            r_s.text = "Generated by Cipher AI"
            r_s.font.size = Pt(14)
            r_s.font.color.rgb = COLOR_ACCENT

            # ── SAVE ──────────────────────────────────────────────────────
            safe_topic = re.sub(r'[^\w\s-]', '', topic).strip().replace(' ', '_')[:40]
            filename = f"{safe_topic}_{datetime.now().strftime('%H%M%S')}.pptx"
            filepath = os.path.join(OUTPUT_DIR, filename)
            prs.save(filepath)

            return f"Presentation created: {filepath} | {len(slides_data['slides'])} slides on '{topic}'."

        except Exception as e:
            return f"PPTX Forge error: {e}"

    def _generate_content(self, topic: str) -> dict:
        """Use TurboBrain to generate structured slide content."""
        try:
            from skills.turbo_brain import turbo_think

            prompt = (
                f"Generate a professional presentation outline on the topic: '{topic}'.\n"
                f"Respond ONLY in this exact JSON format with no extra text:\n"
                f'{{\n'
                f'  "title": "Presentation Title",\n'
                f'  "subtitle": "One line subtitle",\n'
                f'  "closing": "Closing message",\n'
                f'  "slides": [\n'
                f'    {{"heading": "Slide 1 Title", "bullets": ["Point 1", "Point 2", "Point 3", "Point 4"]}},\n'
                f'    {{"heading": "Slide 2 Title", "bullets": ["Point 1", "Point 2", "Point 3", "Point 4"]}}\n'
                f'  ]\n'
                f'}}\n'
                f"Generate exactly 5 content slides. Keep bullet points concise (under 15 words each)."
            )

            result = turbo_think(prompt)

            # Parse JSON from LLM response
            import json
            # Strip markdown fences if present
            result = re.sub(r'```json|```', '', result).strip()
            data = json.loads(result)
            return data

        except Exception:
            # Fallback: static structure if LLM fails or JSON malformed
            return {
                "title": topic.title(),
                "subtitle": f"A comprehensive overview",
                "closing": "Thank You",
                "slides": [
                    {"heading": "Introduction", "bullets": [
                        f"Overview of {topic}",
                        "Key concepts and background",
                        "Why this topic matters",
                        "Scope of this presentation"
                    ]},
                    {"heading": "Core Concepts", "bullets": [
                        "Fundamental principles",
                        "Key terminology and definitions",
                        "How the system works",
                        "Main components involved"
                    ]},
                    {"heading": "Key Benefits", "bullets": [
                        "Primary advantages",
                        "Real-world applications",
                        "Impact and outcomes",
                        "Competitive advantages"
                    ]},
                    {"heading": "Challenges & Solutions", "bullets": [
                        "Common challenges faced",
                        "Proven solutions and approaches",
                        "Best practices",
                        "Lessons learned"
                    ]},
                    {"heading": "Conclusion", "bullets": [
                        "Summary of key points",
                        "Actionable next steps",
                        "Future outlook",
                        "Final recommendations"
                    ]},
                ]
            }

    def _fill_background(self, slide, color):
        """Fill slide background with a solid color."""
        from pptx.util import Inches
        bg = slide.shapes.add_shape(
            1,  # MSO_SHAPE_TYPE.RECTANGLE
            0, 0,
            Inches(13.33), Inches(7.5)
        )
        bg.fill.solid()
        bg.fill.fore_color.rgb = color
        bg.line.fill.background()
        # Push to back
        sp = bg._element
        slide.shapes._spTree.remove(sp)
        slide.shapes._spTree.insert(2, sp)

    def _add_rect(self, slide, left, top, width, height, color):
        """Add a colored rectangle (used for accent bars and dividers)."""
        shape = slide.shapes.add_shape(1, left, top, width, height)
        shape.fill.solid()
        shape.fill.fore_color.rgb = color
        shape.line.fill.background()